//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.android.edc.activity;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup.LayoutParams;
import android.widget.Button;
import android.widget.CheckBox;
import android.widget.EditText;
import android.widget.LinearLayout;
import android.widget.TextView;
import com.android.edc.R.id;
import com.android.edc.R.layout;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class DustJobDetailsActivity_
    extends DustJobDetailsActivity
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
        setContentView(layout.activity_dust_job_details);
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static DustJobDetailsActivity_.IntentBuilder_ intent(Context context) {
        return new DustJobDetailsActivity_.IntentBuilder_(context);
    }

    public static DustJobDetailsActivity_.IntentBuilder_ intent(android.app.Fragment fragment) {
        return new DustJobDetailsActivity_.IntentBuilder_(fragment);
    }

    public static DustJobDetailsActivity_.IntentBuilder_ intent(android.support.v4.app.Fragment supportFragment) {
        return new DustJobDetailsActivity_.IntentBuilder_(supportFragment);
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        edittext_trailer_03 = ((EditText) hasViews.findViewById(id.edittext_trailer_03));
        edittext_notes = ((EditText) hasViews.findViewById(id.edittext_notes));
        checkbox_op4_01 = ((CheckBox) hasViews.findViewById(id.checkbox_op4_01));
        edittext_truck_02 = ((EditText) hasViews.findViewById(id.edittext_truck_02));
        edittext_operator_02 = ((EditText) hasViews.findViewById(id.edittext_operator_02));
        mProgress_dialog = ((LinearLayout) hasViews.findViewById(id.progress_dialog));
        edittext_operator_04 = ((EditText) hasViews.findViewById(id.edittext_operator_04));
        edittext_location_number = ((EditText) hasViews.findViewById(id.edittext_location_number));
        edittext_date = ((EditText) hasViews.findViewById(id.edittext_date));
        checkbox_op3_02 = ((CheckBox) hasViews.findViewById(id.checkbox_op3_02));
        edittext_trailer_04 = ((EditText) hasViews.findViewById(id.edittext_trailer_04));
        edittext_downhole_location = ((EditText) hasViews.findViewById(id.edittext_downhole_location));
        edittext_truck_04 = ((EditText) hasViews.findViewById(id.edittext_truck_04));
        btn_clear = ((Button) hasViews.findViewById(id.btn_clear));
        btn_add_signature = ((Button) hasViews.findViewById(id.btn_add_signature));
        btn_save = ((Button) hasViews.findViewById(id.btn_save));
        checkbox_op1_01 = ((CheckBox) hasViews.findViewById(id.checkbox_op1_01));
        edittext_supervisor_name = ((EditText) hasViews.findViewById(id.edittext_supervisor_name));
        edittext_pailofdust = ((EditText) hasViews.findViewById(id.edittext_pailofdust));
        edittext_hogg = ((EditText) hasViews.findViewById(id.edittext_hogg));
        edittext_client_name = ((EditText) hasViews.findViewById(id.edittext_client_name));
        checkbox_op2_02 = ((CheckBox) hasViews.findViewById(id.checkbox_op2_02));
        checkbox_op4_02 = ((CheckBox) hasViews.findViewById(id.checkbox_op4_02));
        edittext_customer_name = ((EditText) hasViews.findViewById(id.edittext_customer_name));
        edittext_job_end_time = ((EditText) hasViews.findViewById(id.edittext_job_end_time));
        checkbox_op2_01 = ((CheckBox) hasViews.findViewById(id.checkbox_op2_01));
        edittext_truck_03 = ((EditText) hasViews.findViewById(id.edittext_truck_03));
        edittext_job_start_time = ((EditText) hasViews.findViewById(id.edittext_job_start_time));
        checkbox_op3_01 = ((CheckBox) hasViews.findViewById(id.checkbox_op3_01));
        edittext_truck_01 = ((EditText) hasViews.findViewById(id.edittext_truck_01));
        edittext_operator_03 = ((EditText) hasViews.findViewById(id.edittext_operator_03));
        edittext_ar_edc_so = ((EditText) hasViews.findViewById(id.edittext_ar_edc_so));
        edittext_equipment_hrs_end = ((EditText) hasViews.findViewById(id.edittext_equipment_hrs_end));
        edittext_trailer_02 = ((EditText) hasViews.findViewById(id.edittext_trailer_02));
        textview_signature_info = ((TextView) hasViews.findViewById(id.textview_signature_info));
        edittext_operator_01 = ((EditText) hasViews.findViewById(id.edittext_operator_01));
        edittext_trailer_01 = ((EditText) hasViews.findViewById(id.edittext_trailer_01));
        edittext_equipment_hrs_start = ((EditText) hasViews.findViewById(id.edittext_equipment_hrs_start));
        edittext_accommodations = ((EditText) hasViews.findViewById(id.edittext_accommodations));
        checkbox_op1_02 = ((CheckBox) hasViews.findViewById(id.checkbox_op1_02));
        {
            View view = hasViews.findViewById(id.btn_clear);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        DustJobDetailsActivity_.this.onClearData();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.btn_save);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        DustJobDetailsActivity_.this.onSaveData();
                    }

                }
                );
            }
        }
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;
        private android.app.Fragment fragment_;
        private android.support.v4.app.Fragment fragmentSupport_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, DustJobDetailsActivity_.class);
        }

        public IntentBuilder_(android.app.Fragment fragment) {
            fragment_ = fragment;
            context_ = fragment.getActivity();
            intent_ = new Intent(context_, DustJobDetailsActivity_.class);
        }

        public IntentBuilder_(android.support.v4.app.Fragment fragment) {
            fragmentSupport_ = fragment;
            context_ = fragment.getActivity();
            intent_ = new Intent(context_, DustJobDetailsActivity_.class);
        }

        public Intent get() {
            return intent_;
        }

        public DustJobDetailsActivity_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (fragmentSupport_!= null) {
                fragmentSupport_.startActivityForResult(intent_, requestCode);
            } else {
                if (fragment_!= null) {
                    fragment_.startActivityForResult(intent_, requestCode);
                } else {
                    if (context_ instanceof Activity) {
                        ((Activity) context_).startActivityForResult(intent_, requestCode);
                    } else {
                        context_.startActivity(intent_);
                    }
                }
            }
        }

    }

}
